# -*- coding: utf-8 -*-
"""Read from file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RZT4OSal8_p0nyInDW1QwDMYt-Zh5_mJ
"""

pip install pandas

import pandas as pd

df = pd.read_csv("/content/sample_data/cust.csv", skiprows = 1)

print(df)

print(df)

